### ISSUE TITLE
Bug in the Energy Flux screen

### ISSUE THREAD

**Issue by rorog2** [RafaelDeJongh/cap#61] opened 2017-08-31 17:14 UTC
When the gate is active, the energy flux screen is not animated

**Comment by glebqip** [comment] 2017-12-31 16:39
Try disable Discord overlay.
Discord overlay broke ALL rendertargets(including all SGC screens). It's looks like screen freeze or just nothing on screen.

**Comment by AlexALX** [comment] 2017-12-31 16:42
I can't reproduce that, it works always for me except when gate is not active what is normal. I'm closing this for now.

**Closed by AlexALX** 2017-12-31 16:42 UTC
